### ISSUE TITLE
로그인 정규표현식 오류

### ISSUE THREAD

**Issue by jeewonMoon** [gusdn3477/OpenYearRound_Project#18]
function CheckUserEmail(){
    let email = document.getElementsByClassName('user-email').value;
    //let regExp = /[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@([s][e][j][o][n][g]).([a][c]).([k][r])$/;
    let regex = /([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;

    if (!regex.test(email)){
        alert("이메일을 확인해주세요.");
        //document.getElementsByClassName("user-email").innerHTML("올바른 이메일을 입력해주세요.");
    }else{
        alert("correct");   //for test
    }
}

가장 최근에 feat 브랜치에 pull request한 코드 같이 봐주시면 됩니다! -> #17 

처음에 ~@sejong.ac.kr로만 로그인 가능하게 하려고 정규표현식(regExp)을 만들었는데 맞게 써도 틀리다고 떠서 
혹시 정규식이 틀렸나 싶어서 주석처리하고 옛날에 썼던 정규식(regex)으로 바꿔서 테스트해봤는데 맞게 
기입해도 틀렸다고 뜹니다.

계속 혼자 이것저것 고쳐도 안돼서 도움  요청합니다...

*정규표현식은 문제가 없는 것 같습니다.

**Comment by eviloliver** [comment]
흐음

**Comment by gusdn3477** [comment]
- getElementByClassName의 경우 해당 클래스를 가지는 요소들을 묶음으로 가져오는 것으로 알고 있습니다. 즉 getElementById와 작동 방식이 다릅니다. email을 alert 혹은 console.log 찍어보시면 undefined 출력되는 것을 알게 되실겁니다.
- getElementByClassName를 getElementById로 수정한 뒤, 이미 id로 적혀있는 exampleInputEmail1, exampleInputEmail2로 실험해 본 결과 correct 뜨는 것을 확인하였습니다. 그러나 직접 해 보시라는 의미에서 제가 수정해서 올리진 않겠습니다.
- 그리고 가급적이면 pull request 시에는 새로운 브랜치 따서 하시는 게 커밋 내역이 깔끔하게 나오니 강력하게 추천드립니다.
