### ISSUE TITLE
브랜치 전략에 대해..

### ISSUE THREAD

**Issue by gusdn3477** [gusdn3477/OpenYearRound_Project#28]
수요일에 말씀드리려 했는데 브랜치 전략에 대해 이야기를 나눠봤으면 합니다.

1) main으로 pull request 하되, 만장일치 혹은 누가 댓글을 남겨야 merge 버튼이 활성화 되게 하기(그 전까지 merge 불가능)
2) 현 상태 유지

사실 지금 지원님, 재호님의 브랜치에서 공동 레포지토리의 메인이 아닌 브랜치로 pull request 하고 있습니다. 
사실, main 브랜치가 아닌 브랜치에는 바로 merge 하셔도 되는데 그 이유는 pull request가 뜨게 되면 바로 체크해서 메인에 적용할 수 있게 하려 함입니다. (즉, merge를 하면 pull request에 안 뜨겠죠)

사실 대부분 협업자 자격을 얻게 되면 그냥 공동 레포지토레에서 각각 브랜치 따서 작업하고, 메인에 merge 하곤 합니다만, 저희는 최대한 안전을 추구하는 방향으로 나아갔기에 이런 방법을 사용하고 있습니다.

물론 잘못된 merge를 취소할 수 있는 방법이 있지만 github desktop에서 지원하는 지 잘 모르겠습니다.
github desktop을 사용하여 쉬운 난이도를 택한 대신 다소 귀찮음을 감수할 수 밖에 없다고 생각하기도 하구요.

그래서 생각해 낸 방법이 1번 방법입니다.
1번 방법으로 하게 되면 여러분은 그냥 공동 repository에서 작업하시면 됩니다. 근데 어차피 커밋 이력은 똑같아요.

아니면 현재 방법에 1번을 추가해도 좋구요. 각자 장단점이 있어서 뭐가 낫다 그르다는 말씀을 못 드리겠습니다!

요약하자면
1번 -> 공동 브랜치에서 각자 작업한다. 충돌 가능성이 높아지지만 해결하는 방법을 배울 수 있고 귀찮음을 줄이고 다양한 기능들을 사용해 볼 수 있다.
2번 -> 안전하고 익숙하다.
여러분들의 생각이 궁금합니다.

**Comment by jeewonMoon** [comment]
저는 지금 하는 방법이 더 나은 것 같은데 어쩌다보니 다른 브랜치들에 pull request 해놓은 걸 main으로 merge하는 작업을 현우님이 다 하고 계셔서 현우님만 괜찮으시면 그대로 가도 좋을 것 같습니다!

**Comment by gusdn3477** [comment]
> 저는 지금 하는 방법이 더 나은 것 같은데 다른 브랜치들에 pull request 해놓은 걸 main으로 merge하는 작업을 현우님이 다 하고 계셔서 현우님만 괜찮으시면 그대로 가도 좋을 것 같습니다!

사실 저도 지금과 같은 상황에선 지금 시스템이 더 낫다고 생각합니다. 일단 알겠습니다.

**Comment by wogha95** [comment]
다른 방법을 사용해도 새로운 경험이 될거라 어떤 방법을 선택해도 좋고
사실 저는 현재 방법이 아직 완전히 익숙하지 않은 상태여서 그대로 유지해도 좋습니다.
지원님이 말씀하신대로 현우님이 pull request 받고 main에 합치는 작업이 괜찮으시다면 현재 방법 유지하고 향후에 경험해도 늦지 않을 거라  생각합니다.

**Comment by gusdn3477** [comment]
> 다른 방법을 사용해도 새로운 경험이 될거라 다른 방법을 선택해도 좋고
> 사실 저는 현재 방법이 아직 완전히 익숙하지 않은 상태여서 그대로 유지해도 좋습니다.
> 지원님이 말씀하신대로 현우님이 pull request 받고 main에 합치는 작업이 괜찮으시다면 현재 방법 유지하고 향후에 경험해도 늦지 않을 거라 생각합니다.

그러면 일단 현 상태 유지하는 것으로 하겠습니다.

**Comment by gusdn3477** [comment]
이슈 닫겠습니다.
